server:
  port: "8090"
  servlet:
    context-path: "/paymentms"

providers:
  loan-system-api:
    local:
      protocol: "http"
      host: "loan-system-api"
      port: "8090"
      basePath: "/loanms"
    mock:
      protocol: "https"
      host: "9fb34c16-f5da-4ed5-b892-66201f97419f.mock.pstmn.io"
      port: "443"
      basePath: ""
