server:
  port: "8090"
  servlet:
    context-path: "/paymentms"

providers:
  loan-system-api:
    local:
      protocol: "http"
      host: "localhost"
      port: "8090"
      basePath: "/loanms"
    mock:
      protocol: "https"
      host: "9d852ed9-df52-4955-8ad7-12fd47d331b1.mock.pstmn.io"
      port: "443"
      basePath: ""